version: 2.1

jobs:
    build:
        docker:
            - image: docker:19.03.12 # Docker image to use

        steps:
            - checkout # Checkout your code repository

            - run:
                  name: Build Docker image
                  command: docker build -t dockercloud101/docker-react -f Dockerfile.dev .

            - run:
                  name: Run tests in Docker container
                  command: docker run -e CI=true dockercloud101/docker-react npm run test
