sudo: required
services:
    - docker
before_install:
    - docker build -t dockercloud101/docker-react -f Dockerfile.dev .
script:
    - docker run -e CI=true dockercloud101/docker-react npm run test
